### ISSUE TITLE
file DOWNLOAD HASH mismatch error 

### ISSUE THREAD

**Issue by imariman** [anirudhb/flutter_packages#2]
I want to use your package but I am getting the error below. Is there any way to solve  file DOWNLOAD HASH mismatch error?

Error Logs:
CMake Error at flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/CMakeLists.txt:11 (file):
  file DOWNLOAD HASH mismatch

    for file: [C:.../windows/plugins/video_player_windows/ffmpeg_libs/ffmpeg-4.4-full_build-shared.7z]
      expected hash: [4aaf80f0ee78a9eb5a1396742fd51d1624a705bfa7ce263e9b440b8be7db5650]
        actual hash: [e5900f6cecd4c438d398bd2fc308736c10b857cd8dd61c11bcfb05bff5d1211a]
             status: [0;"No error"]

CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find FFmpeg (missing: FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIRS
  AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS AVCODEC_LIBRARIES
  AVCODEC_INCLUDE_DIRS AVFILTER_LIBRARIES AVFILTER_INCLUDE_DIRS
  AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS
  SWRESAMPLE_LIBRARIES SWRESAMPLE_INCLUDE_DIRS POSTPROC_LIBRARIES
  POSTPROC_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/FindFFmpeg.cmake:151 (find_package_handle_standard_args)
  flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/CMakeLists.txt:20 (find_package)

**Comment by anirudhb** [comment]
Thanks for reporting. Should be fixed now!

**Comment by imariman** [comment]
The error has changed but still it does not work.

Error:
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find FFmpeg (missing: FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIRS
  AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS AVCODEC_LIBRARIES
  AVCODEC_INCLUDE_DIRS AVFILTER_LIBRARIES AVFILTER_INCLUDE_DIRS
  AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS
  SWRESAMPLE_LIBRARIES SWRESAMPLE_INCLUDE_DIRS POSTPROC_LIBRARIES
  POSTPROC_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/FindFFmpeg.cmake:151 (find_package_handle_standard_args)
  flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/CMakeLists.txt:20 (find_package)

**Comment by anirudhb** [comment]
Hi, should be fixed properly now. Please note that this package is not written for production use, so if you are using it in production I suggest you find a different video player package. Cheers! 🎉

**Comment by imariman** [comment]
Hi, I am still getting an error. But I will use another package for Windows, so don't spend your time on it. Thank you very much for your time and help. :)


CMake Error at flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/CMakeLists.txt:11 (file):
  file DOWNLOAD HASH mismatch

    for file: [C:/Users/{....}/build/windows/plugins/video_player_windows/ffmpeg_libs/ffmpeg-4.4-full_build-shared.7z]
      expected hash: [e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855]
        actual hash: [146d0d5ab6ba50e6813bab47518bdc582abe122bb2d41bcc5609314890df460c]
             status: [0;"No error"]



CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFmpeg (missing: FFMPEG_LIBRARIES FFMPEG_INCLUDE_DIRS
  AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS AVCODEC_LIBRARIES
  AVCODEC_INCLUDE_DIRS AVFILTER_LIBRARIES AVFILTER_INCLUDE_DIRS
  AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS
  SWRESAMPLE_LIBRARIES SWRESAMPLE_INCLUDE_DIRS POSTPROC_LIBRARIES
  POSTPROC_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/FindFFmpeg.cmake:151 (find_package_handle_standard_args)
  flutter/ephemeral/.plugin_symlinks/video_player_windows/windows/CMakeLists.txt:20 (find_package)

**Comment by insinfo** [comment]
@imariman 
I managed to get the plugin to compile and run, so I'm having a problem now with the video flashing.
https://github.com/anirudhb/flutter_packages/issues?q=is%3Aopen+is%3Aissue

**Comment by imariman** [comment]
@insinfo thank you, your solution works, at least I don't get any error at the moment. But still this package is not usable since it has some serious problems. :)
